In [1]:
import pandas as pd

df = pd.read_csv('customer_shopping_behavior_extended.csv')

In [2]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8900 entries, 0 to 8899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             8900 non-null   int64
 1   Age                     8900 non-null   int64
 2   Gender                  8900 non-null   object
 3   Item Purchased          8900 non-null   object
 4   Category                8900 non-null   object
 5   Purchase Amount (USD)   8900 non-null   int64
 6   Location                8900 non-null   object
 7   Size                    8900 non-null   object
 8   Color                   8900 non-null   object
 9   Season                  8900 non-null   object
 10  Review Rating           8812 non-null   float64
 11  Subscription Status     8900 non-null   object
 12  Shipping Type           8900 non-null   object
 13  Discount Applied        8900 non-null   object
 14  Promo Code Used         8900 non-null   object
 15  Previous Purchases      8900 non-null   int64
 16  Payment Method          8900 non-null   object
 17  Frequency of Purchases  8900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 1.2+ MB

In [4]:
df.describe(include= 'all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,8900.000000,8900.000000,8900,8900,8900,8900.000000,8900,8900,8900,8900,8812.000000,8900,8900,8900,8900,8900.000000,8900,8900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Jewelry,Clothing,NaN,California,M,Silver,Spring,NaN,No,Free Shipping,No,No,NaN,Credit Card,Annually
freq,NaN,NaN,6041,403,3975,NaN,228,4034,414,2270,NaN,6528,1533,5105,5105,NaN,1567,1318
mean,4450.500000,44.209888,NaN,NaN,NaN,59.872584,NaN,NaN,NaN,NaN,3.751657,NaN,NaN,NaN,NaN,25.364607,NaN,NaN
std,2569.353031,15.260851,NaN,NaN,NaN,24.115581,NaN,NaN,NaN,NaN,0.733307,NaN,NaN,NaN,NaN,14.521811,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,2.100000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,2225.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,4450.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,6675.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,8900.000000,70.000000,NaN,NaN,NaN,110.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [5]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             88
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [6]:
# impute null value by category means taking median of rating by each category of clothes or footwear etc.
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [7]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [8]:
#  convert columns names into sneak casing
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [9]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [10]:
# create a columns age_group to group customer into group
labels = ['Young Adult','Adult','Middle-aged','Senior']
df['age_group'] = pd.qcut(df['age'], q = 4, labels = labels)

In [11]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [12]:
#create columns purchased_frequency_days (for this we will create a mapping dictionary to map the frequency of purchases to number of days)
print(df["frequency_of_purchases"].unique())

['Fortnightly' 'Weekly' 'Annually' 'Quarterly' 'Bi-Weekly' 'Monthly'
 'Every 3 Months']

In [13]:

frequency_mapping = {
    'Fortnightly' : 14,
    'Weekly' : 7,
    'Monthly' : 30,
    'Quarterly' : 90,
    'Bi-Weekly' : 14,
    'Annually' : 365,
    'Every 3 Months' : 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [14]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [15]:
df[['discount_applied','promo_code_used']].head(5)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes

In [16]:
# can we actually need previous columns with same data inside lets see
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [17]:
# both columns are same so we donth neet both at same time ket delete one columns
df = df.drop('promo_code_used',axis = 1)

In [18]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [19]:
df.to_csv("customer.csv", index=False)

In [ ]:
# !pip install pandas sqlalchemy pymysql
# !pip install cryptography

Requirement already satisfied: cryptography in c:\users\hrish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (49.0.0)
Requirement already satisfied: cffi>=2.0.0 in c:\users\hrish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from cryptography) (2.1.0)
Requirement already satisfied: typing-extensions>=4.13.2 in c:\users\hrish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from cryptography) (4.14.1)
Requirement already satisfied: pycparser in c:\users\hrish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from cffi>=2.0.0->cryptography) (3.0)

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: C:\Users\hrish\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [ ]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

connection_url = URL.create(
    drivername="mysql+pymysql",
    username="root",
    password="Seju@98199",
    host="127.0.0.1",
    port=3306,
    database="shopping_db",
)

engine = create_engine(connection_url)

csv_file = r"D:\sejal\sql-ultimate-course\python sql powerbi project\customer.csv"

df = pd.read_csv(csv_file)

df.to_sql(
    "shopping_data",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data uploaded successfully!")

Data uploaded successfully!